### ISSUE TITLE
Status of import is pending

### ISSUE THREAD

**Issue by hascoulijn** [boboldehampsink/import#21]
When I import a .csv, the status of the import in the history tab is pending. Also, there are no rows added to the the database. We tried the develop branch but this didn't solve it.

The task hud says Importing filename.csv and it seems like it keeps hanging while performing this task.

**Comment by thoughtfulweb** [comment]
I’ve just installed a completely fresh copy of Craft (version 2.3.2625) and the import plugin and everything seems to be working fine. Nothing has changed in my development environment, except perhaps Craft has been updated since I last tackled this, so I’m unable to provide any tips other than try again if you are experiencing this problem.

**Comment by boboldehampsink** [comment]
It's really unreproducable for me too. The useEmailAsUsername issue is another case tho.
