### ISSUE TITLE
Support for multiple locales

### ISSUE THREAD

**Issue by fredrik-sogaard** [boboldehampsink/import#62]
Is there a way to import data into translatable fields?

Maybe it can be done with appending the locale slug in the column names? Like "Title (us_en)", "Title (nb)"

**Comment by boboldehampsink** [comment]
There's no way yet, but I think just having a column "locale" would be sufficient. Let me think about it.

**Comment by fredrik-sogaard** [comment]
OK. We do a lot of multi languages sites, and it would be super helpful! Just let me know if you need help testing anything should you decide to add this feature.

**Comment by proimage** [comment]
Any news on this possible feature? I've got a heavily multi-lingual site I need to convert over ASAP.

**Comment by proimage** [comment]
Sorry to bug you about this, but I've got a meeting tomorrow where the answer to whether Import supports locales or not is crucial. Is there any chance you could give me something more to report other than "I haven't heard back from the dev yet"? :)

Also, I'm hesitant to even mention this, but as things stand now, I'll likely need to have locale support before the end of the year. I know full well that my needs don't in any way dictate your workflow, of course, but it would be very helpful to at least have an idea if locale support is even feasible by then...?

**Comment by boboldehampsink** [comment]
I've added it to the develop branch, would you test it?

**Comment by proimage** [comment]
OMG YES PLZ KTHX! ;)

**Comment by proimage** [comment]
Doesn't work yet; seems to import into the English locale no matter what I do.

Details: Ok, although my site has like 10 locales, I'm focussing on two just for the test - English and Dutch. So I prepared two separate `.csv` files from EE - one with `{body_en}` and the "locale" column set to `en`, and the other with `{body_nl}` and `nl`.

In Craft, all but one of the locales in the section are turned on; Dutch (nl) is on.

I first imported the `en` file in 'Append data' mode, and saw the English contents of the `body` column populating all locales (as I believe is the norm for Craft).

I then imported the `nl` file in 'Replace data' mode, using the `slug` (which comes from EE's `{url_title}`) as the match criteria. Locale is set to the `locale` column, which contains `nl`.

The result is that the 'en' locale contains the Dutch text, and the rest of the locales still have the English text. I've tried variations such as using `"Dutch"` instead of `"nl"` in the `csv`'s `locale` column, but there was no difference.

Am I doing it wrong?

**Comment by boboldehampsink** [comment]
That should be alright. Maybe I have to enabled the locales aswell. Let me look into it.

**Comment by boboldehampsink** [comment]
Could you try it again?

**Comment by proimage** [comment]
I presume with the locale column set to the 2-char code, not the locale's name?

**Comment by boboldehampsink** [comment]
Yes

**Comment by proimage** [comment]
Still imports the Dutch into the English locale...

**Comment by boboldehampsink** [comment]
So you're using the replace function? That means you're using match criteria. Are you matching by locale aswell? Because you should ;-)

**Comment by proimage** [comment]
ORLY? Interesting... I thought that would just be needed to identify which entry the imported content was for. I'll give that a try.

**Comment by proimage** [comment]
Wow, ok, yeah, that works. :p It works! :clap: So much grass!

One remark though... I can't think of a situation where you would import the Locale column without also needing to set it as a match criteria. If that's true, then perhaps hard-code the Criteria checkbox to be ticked (or replace it entirely with an equivalent hidden field) if the Locale column is selected for import?

**Comment by boboldehampsink** [comment]
Done
